shared:
    image: node:8

parameters:
  p1: p1
  p2:
      value: p2
      description: User running build
  p3:
      value: p3
      description: this is a value for p3
  p4: p4
  p5: p5

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - p1: echo $(meta get parameters.p1)
            - p2: echo $(meta get parameters.p2)
            - p3: echo $(meta get parameters.p3)
            - p4: echo $(meta get parameters.p4)
            - p5: echo $(meta get parameters.p5)
